BEGIN;

-- nom de schéma définitif
SET search_path TO psch;

--supprime les tables si elles existent déjà, pour nos tests
DROP TABLE IF EXISTS 
    programmation_cinema, 
    frequentation, 
    seance,
	matches,
    cinema, 
    utilisateur, 
    aire_geographique, 
    film_titre, 
    film,
	calendrier,
	cinema_favori
CASCADE;

--Création de la table film

CREATE table if not exists film (
    id_film INTEGER,
    titre VARCHAR NOT NULL,
    genre VARCHAR,
    duree INTEGER,
    realisateur VARCHAR,
    date_sortie VARCHAR,
    note INTEGER,
    -- La contrainte de clé étrangère
    CONSTRAINT fk_film_titre 
        FOREIGN KEY (id_film) 
        REFERENCES tmp_titre(id_film)
);

-- Remplissage de la table film
INSERT INTO film
(titre, genre, duree, realisateur, date_sortie, note)
SELECT DISTINCT
	titre,
	genre,
	duree,
	realisateur,
	annee_sortie AS date_sortie,
	note_sur_100
FROM tmp_wiki1
where titre is not null
UNION
SELECT DISTINCT
	titre,
	genre,
	duree,
	realisateur,
	annee_sortie AS date_sortie,
	note_sur_100
FROM tmp_wiki2
where titre is not null;
INSERT INTO film
(titre, genre, realisateur)
SELECT DISTINCT
	titre,
	genre,
	realisateur
FROM tmp_programation tp 
where titre is not null;

--importer les id_film depuis tmp_titre
UPDATE film f
SET id_film = t.id_film
FROM tmp_titre t
WHERE f.titre = t.titre  ;

--cette seconde partie de la création de la table film s'étant avérée trop difficile, nous avons eu recours à l'aide d'une intelligence artificielle
--il manque certaines IDs dans id_film. 
--script pour générer automatiquement ces IDs manquantes

--drop la contrainte clé étrangère pour id_film
ALTER TABLE film DROP CONSTRAINT fk_film_titre;

-- remplit les IDs vides avec O pour permettre de passer id_film en NOT NULL
UPDATE film SET id_film = 0 WHERE id_film IS NULL;

--crée une contrainte NOT NULL à id_film
ALTER TABLE film ALTER COLUMN id_film SET NOT NULL;

--génère automatiquement de nouvelles IDs lorsqu'elles sont manquantes, en gardant celles déjà insérées grâce à BY DEFAULT
ALTER TABLE film 
ALTER COLUMN id_film ADD GENERATED BY DEFAULT AS IDENTITY;

--crée de nouvelles IDs pour les lignes où id_film = 0 en s'assurant d'éviter les doublons
SELECT setval(pg_get_serial_sequence('film', 'id_film'), MAX(id_film)) FROM film;

--met à jour uniquement les lignes qui ont l'ID temporaire '0', DEFAULT ne risque plus de faire ders doublons
UPDATE film 
SET id_film = DEFAULT 
WHERE id_film = 0;

--creation de la table film_titre
CREATE TABLE if not exists film_titre AS
SELECT DISTINCT 
    id_film, 
    titre
FROM film;

-- transforme id_film en clé primaire de la table film_titre
ALTER TABLE film_titre
ADD PRIMARY KEY (id_film);

--transformation de id_film dans film en une clé étrangère de film_titre
ALTER TABLE film
ADD CONSTRAINT fk_film_id_titre
FOREIGN KEY (id_film) 
REFERENCES film_titre(id_film);


--Création de la table aire_geographique 

create table if not exists aire_geographique
(
	id_aire_geographique INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	commune VARCHAR NOT NULL,
	code_insee VARCHAR NOT NULL,  
	code_departement VARCHAR NOT NULL,
	region INTEGER NOT NULL,
	nom_region VARCHAR,
	nb_habitants INTEGER
);

--Remplissage de la table aire_geographique
insert into aire_geographique 
(commune, code_insee, code_departement, region, nom_region, nb_habitants)
select distinct 
	a.commune, 
	a.code_insee, 
	a.departement as code_departement, 
	a.region_cnc as region,
	a.region_administrative as nom_region,
	a.population_commune as nb_habitants
from tmp_cnc a;

--Création de la table utilisateur, qui reste vide pour l'instant

create table if not exists utilisateur
(
	id_utilisateur INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY key,
	nom_utilisateur varchar UNIQUE,
	nom VARCHAR,
	date_naissance date,
	email VARCHAR(150) UNIQUE NOT NULL,
    motdepasse VARCHAR(255) NOT NULL,
	bio TEXT,
	photo_url VARCHAR (255)
);

--Création de la table cinema 
create table if not exists cinema
(
	id_cinema INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_aire_geographique INTEGER,
	nom_cinema VARCHAR NOT NULL,
	adresse VARCHAR,
	commune VARCHAR, 
	longitude REAL,
	latitude REAL,
	numero_uu VARCHAR,
	ecrans INTEGER,
	fauteuils INTEGER,
	FOREIGN KEY (id_aire_geographique) REFERENCES aire_geographique(id_aire_geographique)
);

--remplissage de la table "cinema"

INSERT INTO cinema
(nom_cinema, adresse, commune, longitude, latitude, numero_uu, ecrans, fauteuils)
SELECT DISTINCT 
	nom_cinema, 
	adresse, 
	commune,
	longitude,
	latitude,
	n_uu AS numero_uu, 
	ecrans,
	fauteuils
FROM tmp_cnc ; 

--Création de la table séance

create table if not exists seance
(
	id_seance INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_film INTEGER,
	id_cinema INTEGER,
	titre varchar,
	nom_cinema varchar,
	debut TIMESTAMP,
	fin TIMESTAMP,
	ST BOOLEAN,
	version VARCHAR,
	nb_places INTEGER,
	FOREIGN KEY (id_film) REFERENCES film_titre(id_film),
	FOREIGN KEY (id_cinema) REFERENCES cinema(id_cinema)
);
--Remplissage de la table seance
INSERT INTO seance
(titre, nom_cinema, debut, fin, ST, version, nb_places)
SELECT DISTINCT
	titre,
	nom_cinema,
	debut_seance AS debut,
	fin_seance AS fin,
	sous_titres AS ST,
	version_audio AS version,
	nbr_place AS nb_places
FROM tmp_programation ;

--Création de la table matches qui reste vide pour l'instant

create table if not exists matches
(
	id_matches INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	id_utilisateur1 INTEGER,
	id_utilisateur2 INTEGER,
	id_seance INTEGER,
	statut VARCHAR(20) DEFAULT 'en_attente',
	FOREIGN KEY (id_utilisateur1) REFERENCES utilisateur(id_utilisateur),
	FOREIGN KEY (id_utilisateur2) REFERENCES utilisateur(id_utilisateur),
	FOREIGN KEY (id_seance) REFERENCES seance(id_seance)
);

-- Creation table fréquentation 

create table if not exists frequentation
--notes: FOREIGN KEY ne fonctionne pas tant que cinema n'est pas créé mais cinema a besoin de frequentation pour être créé: problème. table jointe
(
	id_cinema INTEGER,
	nom_cinema varchar,
	adresse_cinema VARCHAR,
	evolution_entrees INTEGER,
	entrees_2021 INTEGER,
	entrees_2022 INTEGER,
	entrees_2023 INTEGER,
	entrees_2024 INTEGER,
	FOREIGN KEY (id_cinema) REFERENCES cinema(id_cinema)
);

-- Remplissage de la table fréquentation 
INSERT INTO frequentation
(nom_cinema, adresse_cinema, evolution_entrees, entrees_2021, entrees_2022, entrees_2023, entrees_2024)
SELECT distinct
	tec.nom_cinema,
	tec.adresse as adresse_cinema,
	tec.evolution_entrees,
	tec.entree_21 AS entrees_2021, 
	tec.entree_22 AS entrees_2022, 
	tc.entree_23 AS entrees_2023,
	tc.entree_24 AS entrees_2024
FROM tmp_cnc tc 
full join tmp_etab_cine tec
on tc.adresse = tec.adresse;

--Création de la table programmation_cinema
create table if not exists programmation_cinema
(
	id_cinema INTEGER, 
	nom_cinema VARCHAR, 
	adresse_cinema VARCHAR,
	seances_annuelles INTEGER,
	art_et_essai BOOL,
	nb_films_inedits INTEGER,
	nb_films_programmes INTEGER,
	pdm_fr INTEGER,
	pdm_us INTEGER,
	pdm_ue INTEGER,
	pdm_autres_films INTEGER,
	pdm_art_et_essai INTEGER,
	FOREIGN KEY (id_cinema) REFERENCES cinema(id_cinema)
);


--remplissage de la table programmation_cinema
INSERT INTO programmation_cinema
(nom_cinema, adresse_cinema, seances_annuelles, art_et_essai, nb_films_inedits, nb_films_programmes, pdm_fr, pdm_us, pdm_ue, pdm_autres_films, pdm_art_et_essai)
SELECT DISTINCT 
	nom_cinema,
	adresse as adresse_cinema,
	seances_annuelles,
	art_et_essai, 
	nb_films_inedits,
	nb_films_programmes,
	pdm_films_francais AS pdm_fr,
	pdm_films_americains AS pdm_us,
	pdm_films_europeens AS pdm_ue,
	pdm_autres_films AS pdm_autres_films,
	pdm_films_ae AS pdm_art_et_essai
FROM tmp_cnc ;

--création de deux tables vides qui seront remplies par les données de l'application

create table if not exists calendrier
(
	id_utilisateur INTEGER NOT NULL,
	id_seance INTEGER,
	FOREIGN KEY (id_utilisateur) REFERENCES utilisateur(id_utilisateur),
	FOREIGN KEY (id_seance) REFERENCES seance(id_seance)
);

create table if not exists cinema_favori
(
	id_utilisateur INTEGER NOT NULL,
	id_cinema INTEGER,
	FOREIGN KEY (id_utilisateur) REFERENCES utilisateur(id_utilisateur),
	FOREIGN KEY (id_cinema) REFERENCES cinema(id_cinema)
);

COMMIT ;
